spring:
  datasource:
  #url: jdbc:mysql://localhost:3306/molarisse_db?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/molaris_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ""  # Replace with your actual MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: arouayoussef920@gmail.com
    password: adfi vhyo eixz nibr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
  mailing:
    frontend:
      activation: http://localhost:4200/activate-account

server:
  port: 8080
